# Generated by Django 4.1 on 2022-08-17 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(blank=True, choices=[('Bronze', 'Globalnet Bronze'), ('Silver', 'Globalnet Silver'), ('Gold', 'Globalnet Gold')], max_length=6)),
                ('primary_phone_number', models.CharField(max_length=14, unique=True)),
                ('other_phone_number', models.CharField(blank=True, max_length=14)),
                ('subscribed_company', models.CharField(choices=[('Robi', 'Robi'), ('Airtel', 'Airtel'), ('Grameenphone', 'Grameenphone'), ('Teletalk', 'Teletalk')], max_length=14)),
                ('contract_initiated', models.DateTimeField(auto_now_add=True)),
                ('phone_number_owner', models.CharField(default=models.CharField(choices=[('Robi', 'Robi'), ('Airtel', 'Airtel'), ('Grameenphone', 'Grameenphone'), ('Teletalk', 'Teletalk')], max_length=14), max_length=100)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubscriptionInfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contract_initiated'],
            },
        ),
    ]
