# Generated by Django 4.1 on 2022-08-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninfo',
            name='subscription_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='phone_number_owner',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
