# Generated by Django 4.1 on 2022-08-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_subscriptioninfo_subscription_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninfo',
            name='contract_remaining',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
