# Generated by Django 4.1 on 2022-08-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_subscriptioninfo_contract_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptioninfo',
            name='contract_remaining',
        ),
    ]
